#!/bin/sh
while read file; do
    case "$1" in
        "w") /home/sohan/.local/bin/wal -i "$file" && xrdb -merge ~/.cache/wal/colors.Xresources && swaymsg "output * bg \"$file\" fill" ;;
    esac
done
