shell /bin/zsh
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
font_size        12.5
scrollback_lines 10000
enable_audio_bell no
hide_window_decorations yes

include ~/.cache/wal/colors-kitty.conf

background_opacity 0.93
dynamic_background_opacity yes
