[manager]
cwd             = { fg = "#F0A000" }
hovered         = { fg = "#F0A000", bg = "#3A2300", bold = true }
previewed       = { bg = "#0F0900" }
count_copied    = { fg = "#6B9000" }
count_cut       = { fg = "#C03000" }
count_selected  = { fg = "#FFD060" }
border_symbol   = "│"
border_style    = { fg = "#7A4A00" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3A2300", bg = "#3A2300" }
mode_normal     = { fg = "#070500", bg = "#C87A0A", bold = true }
mode_select     = { fg = "#070500", bg = "#6B9000", bold = true }
mode_unset      = { fg = "#070500", bg = "#C03000", bold = true }
progress_label  = { fg = "#F0A000", bold = true }
progress_normal = { fg = "#C87A0A", bg = "#070500" }
progress_error  = { fg = "#C03000", bg = "#070500" }
permissions_t   = { fg = "#6B9000" }
permissions_r   = { fg = "#FFD060" }
permissions_w   = { fg = "#C03000" }
permissions_x   = { fg = "#6B9000" }
permissions_s   = { fg = "#7A4A00" }

[input]
border   = { fg = "#F0A000" }
title    = { fg = "#F0A000" }
value    = { fg = "#C87A0A" }
selected = { reversed = true }

[select]
border   = { fg = "#F0A000" }
active   = { fg = "#FFD060" }
inactive = { fg = "#7A4A00" }

[which]
cols            = 3
mask            = { bg = "#0F0900" }
cand            = { fg = "#FFD060" }
rest            = { fg = "#7A4A00" }
desc            = { fg = "#FF7800" }
separator       = "  "
separator_style = { fg = "#7A4A00" }

[notify]
title_info  = { fg = "#6B9000" }
title_warn  = { fg = "#FFD060" }
title_error = { fg = "#C03000" }
icon_info   = ""
icon_warn   = ""
icon_error  = ""

[help]
on      = { fg = "#F0A000" }
exec    = { fg = "#6B9000" }
desc    = { fg = "#C87A0A" }
hovered = { fg = "#F0A000", bg = "#3A2300", bold = true }
footer  = { fg = "#7A4A00", bg = "#070500" }

[filetype]
rules = [
  { mime = "image/*",                      fg = "#FF7800" },
  { mime = "video/*",                      fg = "#C87A0A" },
  { mime = "audio/*",                      fg = "#FFD060" },
  { mime = "application/zip",              fg = "#C03000" },
  { mime = "application/gzip",             fg = "#C03000" },
  { mime = "application/x-tar",            fg = "#C03000" },
  { mime = "application/x-bzip2",          fg = "#C03000" },
  { mime = "application/x-7z-compressed",  fg = "#C03000" },
  { mime = "application/x-rar",            fg = "#C03000" },
  { url = "*.toml", fg = "#FFD060" },
  { url = "*.yaml", fg = "#F0A000" },
  { url = "*.yml",  fg = "#F0A000" },
  { url = "*.json", fg = "#FFD060" },
  { url = "*.md",   fg = "#6B9000" },
  { url = "*",      fg = "#C87A0A" },
]
